spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:appdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:dbpass}
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: ${SMTP_HOST:smtp-mail.outlook.com}
    port: 587
    username: ${SMTP_LOGIN}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:da7887D&*SD(*@0f)(_F89sd()N&lasc90XS89*(XYa-0mdkçÇs&*346S78DS878D%8hf0l2*@())fF*D92sanFd8s9fghmvnzZ98C7&&*((sanc21xcz}
  expiration-time: ${JWT_EXPIRATION_TIME:3600}
  issuer: ${JWT_ISSUER:EnvoltaGroup}